version: "3.9"
services:
  backend:
    build: ./backend
    container_name: puiflix_backend
    ports:
      - "8000:8000"
    volumes:
      - C:/Users/Mauro/Downloads/movies:/app/movies   # Local movies folder
      - ./backend/posters:/app/posters
      - ./backend/static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
      - TMDB_API_KEY=${TMDB_API_KEY}
    networks:
      - puiflix_net

  frontend:
    build: ./frontend
    container_name: puiflix_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - puiflix_net

networks:
  puiflix_net:
    driver: bridge
